# velocity controllers ---------------------------------------
left_robotiq:
  left_f0_j1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_f0_j1
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  left_f1_j1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_f1_j1
    pid: {p: 10.0, i: 0.0, d: 0.0}

  left_f2_j1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_f2_j1
    pid: {p: 10.0, i: 0.0, d: 0.0}

  left_f1_j0_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_f1_j0
    pid: {p: 10.0, i: 0.0, d: 0.0}

  left_f2_j0_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_f2_j0
    pid: {p: 10.0, i: 0.0, d: 0.0}

  left_f0_j2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_f0_j2
    pid: {p: 10.0, i: 0.0, d: 0.0}

  left_f1_j2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_f1_j2
    pid: {p: 10.0, i: 0.0, d: 0.0}

  left_f2_j2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_f2_j2
    pid: {p: 10.0, i: 0.0, d: 0.0}

  left_f0_j3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_f0_j3
    pid: {p: 10.0, i: 0.0, d: 0.0}

  left_f1_j3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_f1_j3
    pid: {p: 10.0, i: 0.0, d: 0.0}

  left_f2_j3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: left_f2_j3
    pid: {p: 10.0, i: 0.0, d: 0.0}
   
