 - name: /right_robotiq/right_hand_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - right_f0_j1
      - right_f1_j1
      - right_f2_j1
      - right_f1_j0
      - right_f2_j0
      - right_f0_j2
      - right_f1_j2
      - right_f2_j2
      - right_f0_j3
      - right_f1_j3
      - right_f2_j3
