# position controllers ---------------------------------------
right_robotiq:
  right_f0_j1_position_controller:
    type: position_controllers/jointpositioncontroller
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}
    
  right_f1_j1_position_controller:
    type: position_controllers/jointpositioncontroller
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  right_f2_j1_position_controller:
    type: position_controllers/jointpositioncontroller
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  right_f1_j0_position_controller:
    type: position_controllers/jointpositioncontroller
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  right_f2_j0_position_controller:
    type: position_controllers/jointpositioncontroller
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  right_f0_j2_position_controller:
    type: position_controllers/jointpositioncontroller
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  right_f1_j2_position_controller:
    type: position_controllers/jointpositioncontroller
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  right_f2_j2_position_controller:
    type: position_controllers/jointpositioncontroller
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  right_f0_j3_position_controller:
    type: position_controllers/jointpositioncontroller
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  right_f1_j3_position_controller:
    type: position_controllers/jointpositioncontroller
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}

  right_f2_j3_position_controller:
    type: position_controllers/jointpositioncontroller
    joint: r_shoulder_pitch
    pid: {p: 10.0, i: 0.0, d: 0.0}
   
