joint_limits:
  right_f0_j1:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: true
    max_acceleration: 2.4
  right_f1_j1:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: true
    max_acceleration: 2.4
  right_f2_j1:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: true
    max_acceleration: 2.4
  right_f1_j0:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: true
    max_acceleration: 2.4
