# trajectory controllers ---------------------------------------
  left_hand_traj_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - left_f0_j1
      - left_f1_j1
      - left_f2_j1
      - left_f1_j0
      - left_f2_j0
      - left_f0_j2
      - left_f1_j2
      - left_f2_j2
      - left_f0_j3
      - left_f1_j3
      - left_f2_j3
    constraints:
      goal_time: &goal_time_constraint 0.2
      left_f0_j1:
        goal: &goal_pos_constraint 0.1
      left_f1_j1:
        goal: *goal_pos_constraint
      left_f2_j1:
        goal: *goal_pos_constraint
      left_f1_j0:
        goal: *goal_pos_constraint
      left_f2_j0:
        goal: *goal_pos_constraint
      left_f0_j2:
        goal: *goal_pos_constraint
      left_f1_j2:
        goal: *goal_pos_constraint
      left_f2_j2:
        goal: *goal_pos_constraint
      left_f0_j3:
        goal: *goal_pos_constraint
      left_f1_j3:
        goal: *goal_pos_constraint
      left_f2_j3:
        goal: *goal_pos_constraint

    stop_trajectory_duration: 0.0

  right_hand_traj_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - right_f0_j1
      - right_f1_j1
      - right_f2_j1
      - right_f1_j0
      - right_f2_j0
      - right_f0_j2
      - right_f1_j2
      - right_f2_j2
      - right_f0_j3
      - right_f1_j3
      - right_f2_j3
    constraints:
      goal_time: *goal_time_constraint
      right_f0_j1:
        goal: *goal_pos_constraint
      right_f1_j1:
        goal: *goal_pos_constraint
      right_f2_j1:
        goal: *goal_pos_constraint
      right_f1_j0:
        goal: *goal_pos_constraint
      right_f2_j0:
        goal: *goal_pos_constraint
      right_f0_j2:
        goal: *goal_pos_constraint
      right_f1_j2:
        goal: *goal_pos_constraint
      right_f2_j2:
        goal: *goal_pos_constraint
      right_f0_j3:
        goal: *goal_pos_constraint
      right_f1_j3:
        goal: *goal_pos_constraint
      right_f2_j3:
        goal: *goal_pos_constraint

    stop_trajectory_duration: 0.0
